### ISSUE TITLE
jest & snapshot testing support

### ISSUE THREAD

**Issue by markoshust** [react-theming/storybook-addon-material-ui#57]
I'm trying to run storyshots (https://storybooks.js.org/docs/react-storybook/testing/structural-testing/), but it is not working. Here is the terminal output from running storyshots with one component wrapping the LoadingCircularProgress component:

```
> yarn test-storybook
yarn test-storybook v0.23.4
$ storyshots 
=> Loading custom .babelrc

loading.LoadingCircularProgress
Warning: Failed context type: The context `muiTheme` is marked as required in `CircularProgress`, but its value is `undefined`.
    in CircularProgress (created by LoadingCircularProgress)
    in div (created by LoadingCircularProgress)
    in LoadingCircularProgress

✗ default: ERROR
  TypeError: Cannot read property 'prepareStyles' of undefined
      at CircularProgress.render (/Users/markshust/Sites/foo/src/node_modules/material-ui/CircularProgress/CircularProgress.js:183:48)
      at /Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:796:21
      at measureLifeCyclePerf (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:795:25)
      at ReactCompositeComponent._renderValidatedComponent (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:822:32)
      at ReactCompositeComponent.performInitialMount (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:362:30)
      at ReactCompositeComponent.mountComponent (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactTestComponent.ReactMultiChild.Mixin.mountChildren (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactMultiChild.js:238:44)
      at ReactTestComponent.mountComponent (/Users/markshust/Sites/foo/src/node_modules/react-test-renderer/lib/ReactTestRenderer.js:62:10)
```

Here is my config.js file, which works perfectly with storybook:

```
import React from 'react';
import { addDecorator, configure } from '@kadira/storybook';
import { muiTheme } from 'storybook-addon-material-ui';
import theme from '../imports/client/theme/muiTheme';

const muiThemeDecorator = (story) => (
  <MuiThemeProvider>
    <div className="row around-xs">
      {story()}
    </div>
  </MuiThemeProvider>
);
const req = require.context('../imports/client', true, /stories\/.*/);

addDecorator(muiTheme(theme));

const loadStories = () => {
  req.keys().forEach((filename) => req(filename));
};

configure(loadStories, module);
```

**Comment by UsulPro** [comment]
There was a storybook issue with spin shots and require.context. Though not sure is it solved in the latest version.
